export interface ChatResponse {
    id: string,
    prompt: string,
    inputText?: string,
    responseText?: string,
    errorMessage?: string,
    currentStage: number,
    stageUpdatedAt?: Date,
    stageUpdatedById?: string,
    stageUpdatedByName?: string,
    validated: number,
    lastValidatedAt?: Date,
    lastValidatedById?: string,
    lastValidatedByName?: string,
    processed: number,
    lastProcessedAt?: Date,
    lastProcessedById?: string,
    lastProcessedByName?: string,
    deleted?: number,
    deletedAt?: Date,
    deletedById?: string,
    deletedByName?: string,
    createdAt: Date,
    createdById: string
    createdByName: string
}
